version: "3.8"

services:

  tesseract:
    container_name: tesseract
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"
    environment:
      - LOG_LEVEL=DEBUG

      # Specify the Label Studio URL and API key to access
      # uploaded, local storage and cloud storage files.
      # Do not use 'localhost' as it does not work within Docker containers.
      # Use prefix 'http://' or 'https://' for the URL always.
      # Determine the actual IP using 'ifconfig' (Linux/Mac) or 'ipconfig' (Windows).
      - LABEL_STUDIO_HOST=http://host.docker.internal:8080
      # specify the access token for the label studio if you use file upload
      - LABEL_STUDIO_ACCESS_TOKEN=5b51da8eb8d6819d054b44dc9bb942d097a7c416
      # set these variables to use Minio as a storage backend
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=adminpassminiO
      - AWS_ENDPOINT=http://host.docker.internal:9000

  minio:
    container_name: minio
    image: bitnami/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpassminiO
      - MINIO_API_CORS_ALLOW_ORIGIN=*
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ".data/storage:/data"
    command: server /data --console-address ":9001"

